const strings = {
  LOGIN: 'L o g i n',
  SIGNUP1: "Don't have an account ? ",
  SIGNUP2: 'Sign up.',
  LOGIN1: 'Already have an account ? ',
  LOGIN2: 'Sign in.',
  REGISTER: 'R e g i s t e r',
  LOGOUT: 'Log Out',
  WELCOME_TO_LOGIN: 'Login',
  WELCOME_TO_REGISTER: 'Register',
  WELCOME_TITLE_APP: 'Toon Kingdom',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  TRYAGAIN: 'Try Again',
  MODALMSG: 'Sorry, something went wrong.',
  FONT: 'Rancho-Regular',
  FAVORITES: 'Favorites',
  ALL: 'Webtoons',
  FORYOU: 'For You',
  MYFAV: 'My Favorite',
  PROFILE: 'My Profile',
  TRYAGAIN: 'Try Again',
  FAVWARN: "You don't have any favorites yet.",
  IMAGE1_URL: 'dummy',
  IMAGE2_URL: 'dummy',
  IMAGE3_URL: 'dummy',
  IMAGE4_URL: 'dummy',
  IMAGE5_URL: 'dummy',
  IMAGE6_URL: 'dummy',
  CREATE_TOON_PAGE: 'My Toon Kingdom',
  TITLE: 'Title',
  EPISODE: 'Episode',
  EPS: 'Ep. ',
  NAME: 'Name',
  IMAGES: 'Images',
  ADD_EPISODE: '+ Episode',
  ADD_IMAGE: '+ Image',
  DELETE: 'Delete',
  SEARCH: 'Search here ..',
  TYPE: 'Type here ..',
};

export default strings;
